using System;
using BankAccounts;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace BankTests
{

    //Manpreet singh sidhu C0726407
    //Arshdeep singh brar C0730228


    [TestClass]
    public class bankaccounttests
    {
        [TestClass]
        public class BankAccountTests
        {
            [TestMethod]
            public void Debit_WithvalidAmount_UpdatesBalance()
            {
                double beginningBalance = 11.99;
                double debitAmount = 4.55;
                double expected = 7.44;
                BankAccount account = new BankAccount("Mr. Bryan Walton", beginningBalance);
                //act
                account.Debit(debitAmount);
                //Assert
                double actual = account.Balance;
                Assert.AreEqual(expected, actual, 0.001, "Account not debited correctly");
            }
            [TestMethod]

            public void Debit_WhenAmountIsLessThanZero_ShouldThrowArguementOutOfRange()
            {
                //Arrange
                double beginningBalance = 11.99;
                double debitAmount = -100.00;
                BankAccount account = new BankAccount("Mr. Bryan Walton", beginningBalance);
                //act
                try
                { account.Debit(debitAmount); }

                catch (ArgumentOutOfRangeException e)
                {
                    StringAssert.Contains(e.Message, BankAccount.DebitAmountLessThanZeroMessage);
                    return;
                }
                Assert.Fail("The expected exception was not thrown.");

            }
            [TestMethod]
            public void Debit_WhenAmountIsMoreThanBalance_ShouldThrowArguementOutOfRange()
            {
                //Arrange
                double beginningBalance = 11.99;
                double debitAmount = 20.00;
                BankAccount account = new BankAccount("Mr. Bryan Walton", beginningBalance);
                //act
                try
                { account.Debit(debitAmount); }
                catch (ArgumentOutOfRangeException e)
                {
                    StringAssert.Contains(e.Message, BankAccount.DebitAmountExceedsBalanceMessage);
                    return;
                }
                Assert.Fail("The expected exception was not thrown.");

            }
        }
    }